# SPDX-FileCopyrightText: Copyright 2023 Open Mobile Platform LLC <community@omp.ru>
# SPDX-License-Identifier: BSD-3-Clause
name: camera_aurora
description: Aurora implementation of the camera plugin.
version: 0.5.0

environment:
  sdk: '>=2.18.6 <4.0.0'
  flutter: ">=3.16.2-1"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  camera_platform_interface: ^2.6.0
  image: ^4.1.3
  async: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      aurora:
        pluginClass: CameraAuroraPlugin
        dartPluginClass: CameraAurora
