name: aurora_photo_test
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  extra_pedantic: ^4.0.0
  auto_route: ^8.1.3
  auto_route_generator: ^8.0.0
  get_it: ^7.7.0
  injectable: ^2.4.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  camera: ^0.10.6
  video_player: ^2.8.6
  logger: ^2.2.0
  i18n:
    path: ../../features/i18n

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
   - assets/